// Generated by ts-to-zod
import { z } from 'zod';

export const commonProxyOptionsSchema = z.object({
  authTokens: z.array(z.string()).optional(),
});

export const mcpStdioServerConfigSchema = z.object({
  command: z.string(),
  args: z.array(z.string()),
  env: z.record(z.string()).optional(),
  cwd: z.string().optional(),
});

export const mcpSSEServerConfigSchema = z.object({
  url: z.string(),
  headers: z.record(z.string()).optional(),
});

export const mcpServerProxyBaseConfigSchema = z.object({
  proxyOptions: commonProxyOptionsSchema.optional(),
});

export const mcpStdioServerProxyConfigSchema =
  mcpServerProxyBaseConfigSchema.and(mcpStdioServerConfigSchema);

export const mcpSSEServerProxyConfigSchema = mcpServerProxyBaseConfigSchema.and(
  mcpSSEServerConfigSchema
);

export const mcpServerProxyConfigSchema = z.union([
  mcpStdioServerProxyConfigSchema,
  mcpSSEServerProxyConfigSchema,
]);

const levelWithSilentOrStringSchema = z.any();

export const proxyServerConfigSchema = z.object({
  options: commonProxyOptionsSchema
    .and(
      z.object({
        logLevel: levelWithSilentOrStringSchema.optional(),
        logPretty: z.boolean().optional(),
      })
    )
    .optional(),
});

export const mcpServerConfigSchema = z.union([
  mcpStdioServerConfigSchema,
  mcpSSEServerConfigSchema,
]);

export const configSchema = z.object({
  proxyServer: proxyServerConfigSchema,
  mcpServers: z.record(mcpServerProxyConfigSchema),
});
